# 参考 :https://qiita.com/msquare33/items/a37f1ee0e486658d10de
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4JLABS_PLUGINS=["apoc"]
      # - NEO4J_apoc_export_file_enabled=true
      # - NEO4J_apoc_import_file_enabled=true
      # - NEO4J_apoc_uuid_enabled=true
      # - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      # - NEO4J_dbms_security_procedures_whitelist=apoc.*
      # - NEO4J_dbms_memory_heap_initial__size=512m
      # - NEO4J_dbms_memory_heap_max__size=2G
      # - NEO4J_dbms_default__listen__address=0.0.0.0
      # - NEO4J_dbms_connector_bolt_listen__address=:7687
      # - NEO4J_dbms_connector_http_listen__address=:7474
      # - NEO4J_dbms_connector_bolt_advertised__address=:7687
      # - NEO4J_dbms_connector_http_advertised__address=:7474
      # - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_default__database=neo4j
    volumes:
      - ./volumes/neo4j/data:/data
      - ./volumes/neo4j/plugins:/plugins
      - ./volumes/neo4j/logs:/logs
      - ./volumes/neo4j/import:/import
      - ./volumes/neo4j/init:/init
      - ./volumes/neo4j/conf:/conf
  phoenix:
    image: arizephoenix/phoenix:latest
    depends_on:
      - db
    ports:
      - 6006:6006  # PHOENIX_PORT
      - 4317:4317  # PHOENIX_GRPC_PORT
      - 9090:9090  # [Optional] PROMETHEUS PORT IF ENABLED
    environment:
      - PHOENIX_SQL_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
